name: app-transfer-api

on:
  create:
     tags:
       - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Set up node"
        uses: actions/setup-node@v3
        with:
          node-version: 14
    
      - name: "Install serverless"
        run: |
          npm install -g serverless
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Serverless deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1
      
      - name: serverless deploy for main
        if: contains(github.ref,'refs/tags/main')
        run : |
          export GO111MODULE=on
          go mod tidy
          rm -rf vendor/
          make build
          rm -f Gopkg.lock Gopkg.toml
          serverless deploy --env main
      
      - name: serverless deploy for stage
        if: contains(github.ref,'refs/tags/stage')
        run : |
          export GO111MODULE=on
          go mod tidy
          rm -rf vendor/
          make build
          rm -f Gopkg.lock Gopkg.toml
          serverless deploy --env stage